config/routes.rb
SampleApp::Application.routes.draw do

  resources :password_resets
  resources :email_confirmations
  resources :users do
    match '/users/:name', :to => 'users#show', :as => :user_path
    member do
      get :following, :followers
    end
  end

  get "sessions/new"

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  root :to => 'pages#home'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Email sent with password reset instructions"
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired!  Please try again"
    elsif @user.update_attributes(params[:user])
      sign_in @user
      redirect_to root_url, :notice => "Password has been reset"
    else
      render :edit
    end
  end

end

app/views/password_resets/edit.html.erb
<h1 id="reset_password">Reset Password</h1>

<%= simple_form_for @user, :validate  => true, :url  => password_reset_path(params[:id]) do |f|  %>
<%= f.input :password, :required => false %>
<%= f.input :password_confirmation %>
<div class="actions">
	<%= f.submit "Change Password" %>
</div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>
<%= form_tag password_resets_path, :method => :post do %>
<div class="field">
	<%= label_tag :email %>
	<%= text_field_tag :email, params[:email] %>
</div>
<div class = "actions"><%= submit_tag "Reset Password" %></div>
<% end %>